spring.application.name=ms-auth

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_db}
spring.datasource.username=${DB_USERNAME:auth_user}
spring.datasource.password=${DB_PASSWORD:auth_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Rutas a las claves PEM montadas en Docker
rsa.private-key-path=${RSA_PRIVATE_KEY_PATH:/keys/private_key.pem}
rsa.public-key-path=${RSA_PUBLIC_KEY_PATH:/keys/public_key.pem}

server.port=8081
