spring:
  application:
    name: bff
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}

services:
  book:
    url: ${BOOK_SERVICE_URL:http://localhost:8082}
  author:
    url: ${AUTHOR_SERVICE_URL:http://localhost:8083}
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

  loan:
    url: ${LOAN_SERVICE_URL:http://localhost:8084}
  penalty:
    url: ${PENALTY_SERVICE_URL:http://localhost:8085}
  inventory:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8086}
  reservation:
    url: ${RESERVATION_SERVICE_URL:http://localhost:8087}
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8088}
  review:
    url: ${REVIEW_SERVICE_URL:http://localhost:8089}

server:
  port: 8080

